### ISSUE TITLE
Move forms to ui-kit

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-ui-kit#41]
Other components such as toggle and forms could be of use but the components in Factoring repo might be the better option since they offer more reusability.
Review both versions with Jan and Megan. Once aligned on which to move, refactor and move. Add storybook support for rendering unit tests.

**Comment by hoffmannjan** [comment]
this will be application dependent. doesn't make sense to move it to the UI kit

**Comment by hoffmannjan** [comment]
closing as won't do
